// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uadsrgjazbtlynuqnsdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZHNyZ2phemJ0bHludXFuc2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjE2NDIsImV4cCI6MjA2NTc5NzY0Mn0.4kpF8uiDrcc6vSu2doLqx68HQ06fSdkFbizoZDcQvRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);